version: '3.1'
services:
  web:
    build: .
    volumes:
      - ./code:/www
    depends_on:
      - db
    ports:
     - "5000:5000"
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=flaskdb
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
